namespace SpriteKind {
    export const objeto_colision = SpriteKind.create()
}
sprites.onOverlap(SpriteKind.Player, SpriteKind.objeto_colision, function (sprite, otherSprite) {
    cambiar_escenario(true)
})
function movimiento_jugador (booleano: boolean) {
    main_character = sprites.create(img`
        . . . . . . f f f f . . . . . . 
        . . . . f f f 2 2 f f f . . . . 
        . . . f f f 2 2 2 2 f f f . . . 
        . . f f f e e e e e e f f f . . 
        . . f f e 2 2 2 2 2 2 e e f . . 
        . . f e 2 f f f f f f 2 e f . . 
        . . f f f f e e e e f f f f . . 
        . f f e f b f 4 4 f b f e f f . 
        . f e e 4 1 f d d f 1 4 e e f . 
        . . f e e d d d d d d e e f . . 
        . . . f e e 4 4 4 4 e e f . . . 
        . . e 4 f 2 2 2 2 2 2 f 4 e . . 
        . . 4 d f 2 2 2 2 2 2 f d 4 . . 
        . . 4 4 f 4 4 5 5 4 4 f 4 4 . . 
        . . . . . f f f f f f . . . . . 
        . . . . . f f . . f f . . . . . 
        `, SpriteKind.Player)
    controller.moveSprite(main_character, 100, 100)
}
function cambiar_escenario (booleano: boolean) {
    sprites.destroy(colision)
    crear_escenario(2)
}
function crear_escenario (id: number) {
    lista_id_escenario = [0, 1, 2]
    lista_escenario = [img`
        111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111
        cce4eceecce4eceecce4eeeecce4eeeecceeeeeecceeeeeecceeeeeecceeeeeecceeeeeecceeeeeeceeeeeeeceeeeeeeceeeeeeeceeeeeeeceeeeeeeceeeeeeeceeeeeeeceeeeeecce4eceecce4eced
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffd
        ffffefffffffefffffffefffffffefffffffefffffffefffffffefffffffeffffffeeffffffeeffffffeeffffffeeffffffeeffffffecffffffefffffffefffffffefffffffefffffffefffffffeffd
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffd
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffd
        fefffffffefffffffefffffffefffffffefffffffefffffffefffffffefffffffeffffffeeffffffeeffffffeeffffffeeffffffecffffffefffffffefffffffefffffffefffffffefffffffefffffd
        fffeeefffffeeefffffeeefffffeeffffffeeffffffeeffffffeeffffffeeffffffeefffffceefffffeeefffffeeefffffeeefffffeeefffffeeefffffeeefffffeeefffffeeefffffeeefffffeeefd
        fffeeefffffeeffffffeeefffffeeffffffeeefffffeeffffffeeefffffeeffffffeeffffffefffffffeeffffffefffffffeeffffffefffffffeeffffffeffffffeeefffffeeffffffeeefffffeeffd
        fffeeeeffffeefeffffeeeeffffeefeffffeeeeffffeffeffffeeeeffffeffeffffeeeeffffeffefffeeeeefffeeffefffeeeeefffeefcefffeeeeefffeefeefffeeeeefffeefeffffeeeeffffeefed
        ffffefffffffffffffffeffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffeffd
        ffffefffffffefffffffefffffffefffffffefffffffefffffffefffffffefffffffefffffffeffffffeeffffffeeffffffecffffffefffffffefffffffefffffffefffffffefffffffefffffffeffd
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffd
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffd
        fefffffffefffffffefffffffefffffffefffffffefffffffefffffffefffffffefffffffefffffffefffffffcffffffecffffffefffffffefffffffefffffffefffffffefffffffefffffffefffffd
        fffeeefffffeeefffffeeffffffeeffffffeeffffffeeffffffeeffffffeeffffffeeffffffeeffffffeefffffceefffffeeefffffeeefffffeeefffffeeefffffeeefffffeeefffffeeefffffeeefd
        fffeeffffffeeffffffeeffffffeeffffffeeffffffeeffffffeeffffffeeffffffeeffffffeeffffffeeffffffecffffffecffffffecffffffecffffffefffffffefffffffeffffffeeffffffeeffd
        fffeefeffffeefeeeeffcefeeeffceceeeffceceeeffeeceeeffeeceeeffeeceeeffeeceeeffeeceeeffeeceeeffeeceeeffeeceeeffeeceeeffeeceecffeeceecffecceecffecffffeefeffffeefed
        ffffefffffffeffe44efe4ee44ece4ee44ece4ee44eceeee44eeeeee44eeeeee44eeeeee44eeeeee44eeeeee4eeeeee44eee4ee44eee4ee44eee4ee44eee4ee44ece4ee44efe4efffffefffffffeffd
        ffffefffffffeffe44eeeece44eeeeee44eeeeee44eeeee444eeeee444eeeee444eeeee44eeeeee44eeeeee44eeeeee44eeeeee44eeeeee44eeeeee44eeeeee44eeeece44eeeecfffffefffffffeffd
        fffffffffffffffeeeeeeceeeeeeeceeeeeeefeeeeeeefeeeeeeefeeeeeeefeeeeeeefeeeeeeefeeeeeeefeeeeeeefeeeeeeefeeeeeeefeeeeeeefeeeeeeefeeeeeeefeeeeeeefffffffffffffffffd
        fefffffffffffffeeee4eeeeeee4eeeeeee4eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee4eeeeeee4eeeeeee4eeeeeee4eeeeeee4eeeeeee4eeeeeee4eeeffffffffffffffffd
        fefffffffefffffeefeeefeeeeeeefeeeeeeefeeeeeeefeeeeeeefeeeeeeefeeeeeeefeeeeeeefeeeeeeefeeeeeeefeeeeeeeceeeeeeeceeceeeeceefeeeeceefeeeeceefeeeecffefffffffefffffd
        fffeeefffffeeffeeeeeeee4eeeeeee4eeeeeee4eeeeeee4eeeeeee4eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee4eeeeeeeffffeeefffffeeefd
        fffeeeeffffeefeeeeeffee4eeeffee4eeeffee4eeefeee4eeefeee4eeefeee2eeffeeeeeeffeeeeeeffeeeeeeffeeeeeeffee2eeeffee4eeeffee4eeeffee4eeeffee4eeeffeeffffeeeeffffeeffd
        fffeeeeffffeefeeeefffeeeeefffeeeeefffeeeeefffeeeeefffeeeeefffeeeeefffeeeeefffeeeeefffeeeeefffeeeeefffeeeeefffeeeeefffeeeecfffeeeecfffeeeefffeeffffeefeffffeefed
        ffffefffffffefffeceeceffeceeeefeeceeeefeeceeeefeeeeeeffeeeeeeffeeeeeeffeeeeeeffeeeeeeffeeeeeeffeeeeeeffeeeeeeffeeeeeeffeeeeeeffeeeeeeffeeeeeeffffffefffffffeffd
        ffffefffffffefffffe4eefffeeeeefffeeeeefffeeeeefffeeeeefffeeeeefffeeeeefffeeeeefffeeeeefffeeeeefffe4eeefffe4eeefffe4eecfffe4eecfffe4eecfffe4eecfffffefffffffeffd
        fffffffffffffffffeeeeeeffeeeeeeffeeeeeeffeeeeeeffeeeeeeffeeeeeeffeeeeeeffeeeeeeffeeeeeeffeeeeeeffeeeeeeffeeeeefffeeeeefffeeeeeffeeeeeeffeeeeeeefffffffffffffffd
        fefffffffefffffffeeeeefffeeeeefffeeeeefffeeeeefffeeeeefffeeeeefffeeeeefffeeeeefffeeeeefffeeeeeffeeeeeeffeeeeeeffeeeeeeffeeeeeeffeeeeefffeeeeefffefffffffefffffd
        feffeffffeffeffffefffffffefffffffefffffffefffffffefffffffefffffffeffffffffffffffffffffffffffffffefffffffefffffffefffffffefffffffefffffffefffffffeffeffffeffeffd
        fffeeffffffeeffffefffffffefffffffcfffffffcfffffffcffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcfffffffcfffffffcfffffffefffffffffeeffffffeeffd
        fffeeffffffeefcefceecccccceeccfffffffffffffffffccceecccccceeccceceeecffceeeeeccccceecccccceecccccceecccccceeccffffffffffffffffffceecccccceeeccffffeeffffffeeffd
        fffeefeffffeefeecebeebbbeebbbbcffffcfffffffffffecbbeebbbeebbbbbbbbbecfcccbddbbbbeebbbbbbeebbbbbbeebbbbbbeebbbbcfffcfffffffffffcccbeebbbbeebbbbcfffeefeffffeefed
        ffffefffffffeffebbbbbbddbbbdddbceceeffeefffffffbbbbbbbddbbbdddddbbcfffccccbdddddbbbdddddbbbdddddbbbdddddbbddddceeeeeffeeffffffcbbbbbbbdbbbdddbcffffefffffffeffd
        ffffefffffffeffcbebbbbbddbbdddbccffffffffffffffebebbbbbddbbddddbbecfffffffccbddddbdddddddbdddbdddbdddddddbdddbccffffffffffffffcbbbbbbbbdbbddddcffffefffffffeffd
        fffffffffffffffebbebbbbbddbdddbcfffffffffffffffcbbebbbbddbbddddbeecfffffffffcbdddbdddddddbddbbdddbdddddddbddbbcfffffffffffffffcbbebbbbbddbddddefffffffffffffffd
        fefffffffefffffebbebbbbbddbdddbceeffefffeffffffcbbbbbbbbdbbdddbbbbcffffffffffcbdbbddddddbbddddddbbddddddbbddddceefffefffefffffcbbebbbbbbdbddddefefffffffefffffd
        feffeffffeffeffebbbbbbbbbbbdbdbccffffffffffffffcbbbbbbbbbbbdbdbbbdcfcccffffffcbdbbbbbbbdbbbbbbbdbbbbbbbdbbbbbbccffffffffffffffcbbbbbbbbbbbddbdcfcffeffffeffeffd
        fffeeefffffeeffeebbbbbbbbbbdddbcfffffffffffffffebbbbbbbbbbbdddbbddccceefffffffcbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbcfffffffffffffffcebbbbbbbbbbddddcfffeeefffffeeffd
        fffeeeeffffeefeeebbbbdbbbbbbddbcefeeffeffffffffeebbbbdbbbbbbdbbbddccebefcecfffcbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbceffeeffefffffffceebbbdbbbbbbbdbcfffeeeeffffeefed
        fffeefeffffeefeebbbbbbbbbdbbbbbfeffefffefffffffcbbbbbbbbdbbbbbbbbdccebeceecfffcebbbbbbbbdbbbbbbbbbbbbbbbdbbbbbceffeeffffffffffcbbbbbbbbbdbbbdbcfffcefeffffcefcd
        ffffefffffffeffebbbbbbbddddddbbffffffffffffffffbbbbbbbbddddddbbbddccebecebefcfcebbbbbbdddddddbbbbbbbbbdddddddbcfffffffffffffffcbbbbbbbdddddddbcffffefffffffeffd
        ffffefffffffeffcbebbbbbdddddddbfcfeecfceffcefffebebbbbbddddddbbbddccebecebeccccbbbbbbbdddddddbbbbbbbbbdddddddbccfceefceefcecffcbbebbbbdddddddbcffffefffffffeffd
        fffffffffffffffebbebddbdddbdddbceeeeeeeeeeeeeffcbbbbdbbddbbddbbbeccfebecebeffccbbbbbdbdddbbddbbbbbbbdbdddbbddbceeeeeeeeeeeeeffcbbebbdbdddbbddbefffffffffffffffd
        fefffffffefffffebbbdddbddbbdddbfeeeeeeeeeeeeeffcbbbddbbddbbddbbbecffcecfcecffcddbbdddbddbbdddbddbbdddbddbbdddbceeeeeeeeeeeeeffcbbbdddbddbbdddbefefffffffefffffd
        fcffeffffcffeffebbddddbdbbddddbfeeeeeeeeeeeeeffebbdddbbdbbdddbbdbecfccffccccbbdddddddbddbddddbdddddddbddbddddbceeeeeeeeeeeeeffcbbddddbddbddddbcfcffeefffcffeefd
        fffeeffffffeeffebdbdddbdddbdddbfeeefeeefeeeffffbbbbddbbddbbddbbdbbbcccccccbbbbbddbbddbbddbbddbbddbbddbbddbbddbcceefceefceefcffcbdbbddbbddbbddbcfffeeffffffeeffd
        fffeefeffffeefebbbbbbdbbbbbbbbbffffffffffffffffebbbbbdbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbcfffffffffffffffcbbbbbdbbbbbbbbbcfffeefeffffeefed
        fffcefcffffcefeebbbbbbdbbbbdddbfcffffffffffffffebbbbbbdbbbbddbbbbbbddbbbbbbddbbbbbbddbbbbbbddbbbbbbddbbbbbbddbccffcfffcfffffffcbbbbbbbdbbbbddbcfffcefcffffcefcd
        ffffefffffffeffebbbbbbddbbbdddbceeeeffeefffffffbbbbbbbddbbbdddddbbbdddddbbbdddddbbbdddddbbbdddddbbddddddbbddddceeeeeffeeffffffcbbbbbbbddbbd1ddcffffefffffffeffd
        ffffefffffffeffcbeebbbbddbbdddbcfffffffffffffffebeebbbbddbbddddddbbddddddbdddbdddbdddddddbdddbdddbdddddddbddbbccffffffffffffffcbbebbbbbddbddddeffffefffffffeffd
        fffffffffffffffebbebebbbddbdddbcfffffffffffffffcbbebbbbddbbddddddbbddddddbdddbdddbdddddddbddbbdddbdddddddbddbbccffffffffffffffcbbebebbbddbddddefffffffffffffffd
        fefffffffefffffebbebbbbbbdbdddbceeffeeffeefffffcbbbbbbbbdbbdddddbbbdddddbbbdddddbbddddddbbddddddbbddddddbbddddceeeffefffefffffcbbebbbbbbdbddddefefffffffefffffd
        fcffeefffcfceefebbbbbbbdbbbdbbbcfffffffffffffffebbbbbbbbbbbdbdddbbbbbbbdbbbbbbbdbbbbbbbdbbbbbbbdbbbbbbbdbbbbbbcfffffffffffffffcbbbbbbbdbbbdbbdcffffeefffcffeefd
        fffeeefffffeeffeebbbbbbbbbbdddbcfffcfffffffffffeebbbbbbbbbbdddbbdbbbbbbbdbbbbbbbdbbbbbbbdbbbbbbbdbbbbbbbdbbbbbccffcfffffffffffcebbbbbbbbbbbdddcfffeeefffffeeffd
        fffeeeeffffeefeeebbebdbbbbbbbdbfefeeffeefffffffcebbebdbbbbbbdbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbcefceeffefffffffceebebdbbbbbbbdbcfffeeeeffffeefed
        fffcefeffffcffcebbbbbbbbddbbbbbfeffefffffffffffcbbbbbbbbdbbbbbbbbbbbbbbddbbbbbbbbbbbbbbddbbbbbbbbbbbbbbddbbbbbccfffeffffffffffcbbbbbbbbddbbbbbcffffefeffffcefcd
        ffffefffffffeffcbbbbbebd1dddddbffffffffffffffffbbbbbbbbddddddbbbbbbbbbbddddddbbbbbbbbbdddddddbbbbbbbbbd1dddddbcfffffffffffffffcbbbbbebd1dddddbcffffefffffffeffd
        ffffefffffffeffcbeebbbbdddddddbfcfeeefeecfeefffebebbbbbddddddbbbbbbbbbdddddddbbbbbbbbbdddddddbbbbbbbbbdddddddbccfceefceefceeffcbeebbbbdddddddbcffffefffffffeffd
        fffffffffffffffebbebddbdddbbddbceee4eee4eee4effcbbbbdbbddbbddbbbbbbddbdddbbddbbbbbbddbdddbbddbbbbbbddbdddbbddbceee44eeeeeeeeffcbbebddbdddbbddbefffffffffffffffd
        fefffffffefffffebbbdddbddbbdddbfeeeeeeeeeeeeeffcbbdddbbddbdddbbddbdddbdddbdddbddbbdddbddbbdddbddbbdddbddbbdddbcceeeeeeeeeeeeffcbbbdddbddbbdddbcfefffffffefffffd
        fcfceefffcfceefcbbddddbdbbddddbfeeeeeeeeeeeeeffebddddbbdbddddbbddddddbddbddddbdddddddbddbddddbdddddddbddbddddbceeeeeeeeeeeeeffcbbddddbdbbddddbcfffceefffcfceefd
        fffeeffffffeeffebdbbddbbddbbddbfcecfcecfcecffffbdbbddbbddbbddbbddbbddbbddbbddbbddbbddbbddbbddbbddbbddbbddbbddbcceeffeeffeeffffcbdbbddbbddbbddbcfffeeffffffeeffd
        fffeefeffffeefebbbbbbdbbbbbbbbbffffffffffffffffccccccccccccccccbbbbbbdbbbbbbbbecccccccccccccccccccccccccccccccffffffffffffffffcbbbbbdbbbbbbbbbcfffeefeffffeefed
        fffcefcffffcefcebbbbbbddbbbdddbfcfccfffcffffffffcfccffccfffffffbbbbbbbdbbbbddbcccfcfffcfffffffffcfefffcfffffffffffefffcfffffffcbbbbbbbdbbbbddbcfffcefcffffcefcd
        ffffefffffffeffcbbbbbbdddbbd1dbceeeeffeeffffffffeeeeffeefffffffbbbbbbbddbbbdddbeeeeeffeefffffffeeeeeffeefffffffeeeeefceeffffffcbbbbbbbddbbd1ddcffffefffffffeffd
        ffffefffffffeffebeebbbbbddbdddbcfffffffffffffffffffffffffffffffebeebbbbddbddddbcffffffffffffffffffffffffffffffffffffffffffffffcbeebbbbbddbddddeffffefffffffeffd
        fffffffffffffffebbebebbbddbdddbcfffffffffffffffffffffffffffffffcbbebebbddbddddbcffffffffffffffffffffffffffffffffffffffffffffffcbbebebbbddbddddefffffffffffffffd
        fefffffffefffffebbbbbbbbbdbdddbceeffeeffeeffffffeeffeeffeefffffcbbbbbbbbdbddddbeeeffeeffeefffffceeffeeffeefffffeeeffefffefffffcbbbbbbbbbdbddddefefffffffefffffd
        fffceefffffceefebbbbbbbdbbbdbdbcfffffffffffffffffffffffffffffffebbbbbbdbbbddbdbcffffffffffffffffffffffffffffffffffffffffffffffcbbbbbbbdbbbdbbdcfffceefffffceefd
        fffeeefffffeeffeebbbbbbbbbbbddbcfffcffffffffffffffccfffffffffffeebbbbbbbbbbdddccffcfffffffffffffffcfffffffffffffffcfffffffffffcebbbbbbbbbbbdddcfffeeefffffeeffd
        fffeeeeffffeefeeebbebdbbbbbbbdbfefeeffeeffffffffefeeffeefffffffcebbbbdbbbbbbdbccefeeffeefffffffccceeffeefffffffefceeffeeffffffceebebdbbbbbbbdbcfffeefeffffeefed
        fffcefcffffcefcebbbbbbbdddbbbbbfcffffffffffffffffffffffffffffffbbbbbbbbddbbbbbcfffffffffffffffffffffffffffffffffffffffffffffffcbbbbbbbbddbbbbbcffffefefffffeffd
        ffffefffffffeffcbbbbbbbd1dddddbffffffffffffffffffffffffffffffffbbbbbbbbddddddbcfffffffffffffffffffffffffffffffffffffffffffffffcbbbbbbbd1dddddbcffffefffffffeffd
        ffffefffffffeffebeebbbbdddddddbfcceeefeeefeecfffcceeeceeeceefffebebbbbbddddddbccceeecceecceeffffceeeceeefeeeffffceeefeeefeeeffcbbebbbbdddddddbcffffefffffffeffd
        fffffffffffffffebbbbddbdddbdddbceee4eeeeeeeeefffeee4eeeeeeeeeffcbbbddbdddbbddbceee44eeeeeeeeeffcee44eeeeeeeecffeee44eeeeeeeeffcbbbbddbdddbbddbefffffffffffffffd
        fefffffffefffffebbbdddbddbbdddbfeeeeeeeeeeeeefffeeeeeeeeeeeeeffcbbdddbbdbbdddbcceeeeeeeeeeeeffffeeeeeeeeeeeeffffeeeeeeeeeeeeffcbbbdddbddbbdddbcfefffffffefffffd
        fffceefffffceefebbddddbdbbddddbfeeeeeeeeeeeeefffeeeeeeeeeeeecffebddddbbdbddddbcceeeeeeeeeeeeffffeeeeeeeeeeeefffceeeeeeeeeeeeffcbbddddbdbbddddbcfffceefffffceefd
        fffeeffffffeeffebbbbddbbdbbbdbbceeefceefcecfcfffeecccecceeccffcbbbbbdbbbdbbbdbcceecceecceeccffffeecceecceeccfffceecceecceeccffcbdbbddbbddbbddbcfffeeffffffeeffd
        fffeefeffffeefebbbbbbdbbbbbbbbbccccccccccccccccccccccccccccccccbbbbbbbbbbbbbbbbcccccccccccccccccccccccccccccccccccccccccccccccebbbbbbbbbbbbbbbcfffeefeffffeefed
        ffffefffffffefcebbbbbbddbbbdddbbbbbdddbbbbbdddbbbbbdddbbbbbddbbbbbbddbbbbbbddbbbbbbddbbbbbbddbbbbbbddbbbbbbddbbbbbbddbbbbbbddbbbbbbddbbbbbbddbcffffefffffffeffd
        ffffefffffffeffcbbbbbbbddbbddddddbbddddddbbddddddbbdddddbbbdddddbbbdddddbbbdddddbbddddddbbddddddbbddddddbbddddddbbd1ddddbbd1ddddbbd1ddddbbd1ddcffffefffffffeffd
        ffffefffffffeffebeebbbbbddbdddddddbddddddbbddbdddbbddddddbbddbdddbbddddddbdddbdddbdddddddbddbbdddbdddddddbddbbdddbdddddddbddbbdddbdddddddbddbbeffffefffffffeffd
        fffffffffffffffebbebebbbddbddddddbbddddddbbddbdddbbddddddbbddbdddbbddddddbdddbdddbdddddddbddbbdddbdddddddbddbbdddbdddddddbddbbdddbdddddddbddbbefffffffffffffffd
        fefffffffefffffebbbbbbbbbbbddddddbbddddddbbdddddbbbdddddbbbdddddbbbdddddbbbdddddbbbdddddbbbdddddbbddddddbbddddddbbddddddbbddddddbbddddddbbddddcfefffffffefffffd
        fffeeefffffeeffebbbbbbbbbbbdbddddbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbdbbbbbbbdbbbbbbbdbbbbbbbdbbbbbbbdbbbbbbcfffceefffffeeefd
        fffeeefffffeeffeebbbbdbbbbbbddbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbdbbbbbbbdbbbbbbbdbbbbbbbdbbbbbcfffeeefffffeeffd
        fffeeeeffffeefeeebbebdbbbbbbbdbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbefffeefeffffeefed
        ffffefffffffeffebbbbbbbdddbbbbbbbbbbbbbdddbbbbbbbbbbbbbdddbbbbbbbbbbbbbddbbbbbbbbbbbbbbddbbbbbbbbbbbbbbddbbbbbbbbbbbbbbddbbbbbbbbbbbbbdddbbbbbcffffefffffffeffd
        ffffefffffffeffcbbbbbbbdddddddbbbbbbbbbdddddddbbbbbbbbbddddddbbbbbbbbbdddddddbbbbbbbbbdddddddbbbbbbbbbdddddddbbbbbbbbbdddddddbbbbbbbbbdddddddbcffffefffffffeffd
        ffffeffffffffffebbebbbbdddbdddbbbbbbbbbddddddbbbbbbbbbbddddddbbbbbbbbbdddddddbbbbbbbbbdddddddbbbbbbbbbdddddddbbbbbbbbbdddddddbbbbbbbbbdddbdddbeffffefffffffeffd
        fffffffffffffffebbbbddbddbbdddbdbbbdddbddbbddbbdbbbddbbddbbddbbdbbbddbdddbbddbbbbbbddbdddbbddbbbbbbddbdddbbddbbbbbbddbdddbbddbdbbbbddbdddbbddbefffffffffffffffd
        fefffffffefffffebbddddbddbddddbddbddddbddbdddbbddbdddbbdbbdddbbddbdddbddbbdddbdddbdddbddbbdddbdddbdddbddbbdddbddbbdddbddbbdddbddbbdddbddbbdddbcfefffffffefffffd
        fffeeffffffeeffebdbdddbdbdbdddbdddbdddbdbdbddbbdddbddbbdbbbddbbddddddbbdbbdddbbddddddbbdbbdddbdddddddbddbbdddbdddddddbdddbdddbdddbdddbdbdbdddbcfffeeefffffeeefd
        fffeeffffffeeffebbbbbdbbdbbbbbbbdbbbbbbbdbbbbbbbdbbbbbbbdbbbbbbbdbbbdbbbdbbbdbbbdbbbdbbbdbbbdbbbbbbbdbbbbbbbdbbbbbbbdbbdbbbbdbbdbbbbdbbdbbbbdbcfffeeffffffeeffd
        fffeefeffffeefebbbbbbdbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbdbcfffeefeffffeefed
        ffffefffffffeffebbbbbbddbbbdddbbbbbdddbbbbbdddbbbbbdddbbbbbdddbbbbbdddbbbbbdddbbbbbdddbbbbbddbbbbbbddbbbbbbddbbbbbbddbbbbbdddbbbbbdddbdbbbdddbcffffefffffffeffd
        ffffefffffffeffcbbbbbbbddbbddddddbbddddddbbddddddbbddddddbbddddddbbdddddbbbdddddbbddddddbbddddddbbddddddbbddddddbbddddddbbddddddbbddddddbbddddcffffefffffffeffd
        fffffffffffffffebbebbbbdddbdddddddbdddddddbddbdddbbddddddbbddbdddbbddddddbddbbdddbdddddddbddbbdddbdddddddbddbbdddbdddddddbddbbdddbdddddddbddbbefffffffffffffffd
        fffffffffffffffebbebebbbddbddddddbbddddddbbddbdddbbddddddbbddbdddbbddddddbbddbdddbdddddddbdddbdddbddddddbbddbbddbbddddddbbddbdddbbddddddbbddbdefffffffffffffffd
        fefffffffefffffebbbbbbbbbdbddddddbbdddbdbbbdddbdbbbdddbdbbbdddbdbbbdddbdbbbdddbdbbbddbddbbbddbddbbbddbddbbbddbddbbdddbddbbdddbddbbdddbddbbdddbcfefffffffefffffd
        fffeeefffffeeffebbbbbbbdbbbdbddbdbbbbbbbdbbbbbbbdbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbdbbbbbbbdbbbbbbbdbbbbbbcfffeeefffffeeefd
        fffeeefffffeefceebbbbdbbbbbbddbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbdbbbbbbbdbbbbbcfffeeeeffffeeffd
        fffeeeeffffeefeeebbebdbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbefffeefeffffeefed
        ffffefffffffeffebbbbbbbdddbdbdbbbbbbbbbdddbdbbbbbbbbbbbdddbdbbbbbbbbbbbdddbbbbbbbbbbbbbdddbbbbbbbbbbbbdddddbdbbbbbbbbbdddbdbdbbbbbbbbbdddbdbdbcffffefffffffeffd
        ffffefffffffeffcbebbbbbdddddddbbbbbbbbbddddddbbbbbbbbbbddddddbbbbbbbbbbddddddbbbbbbbbbdddddddbbbbbbbbbdddddddbbbbbbbbbdddddddbbbbbbbbbdddddddbcffffefffffffeffd
        fffffffffffffffebbebbdbdddbdddbbbbbbbbbdddbdddbbbbbbbbbdddbddbbbbbbbbbddddbddbbbbbbbbbdddddddbbbbbbbdbdddbdddbbbbbbbdbdddbdddbbbbbbbdbdddbdddbefffffffffffffffd
        fefffffffefffffebbbbddbddbbdddbdbbbddbbddbbddbbdbbbddbbddbbddbbdbbbddbbddbbddbbdbbbddbdddbbddbbdbbbddbdddbbddbddbbbddbddbbbddbddbbbddbddbbbddbefffffffffffffffd
        fefffffffefffffebbddddbdbbddddbddbddddbdbbddddbddbddddbdbbdddbbddbdddbddbbdddbdddddddbddbbdddbdddddddbddbbdddbdddddddbddbddddbddbddddbddbddddbcfefffffffefffffd
        fffeeffffffeeffebdbbddbdbdbbdbbdddbbdbbdbdbddbbdddbddbbdddbddbbdddbddbbdddbddbbdddbddbbddbbddbbddbbddbdddbbddbdddbbddbdddbbddbdddbbddbdbdbbddbcfffeeefffffeeefd
        fffeeffffffeefcebbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbddbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbebbbbbbbebbbbcfffeeffffffeeffd
        fffeefeffffeefeeffceeceeffceeceeffeeececffeeececffeeeeecffeeeeebbbbbbdbbbbbbbbecffeeeeecffeeeeecffeeeeecffeeceecffeeceecffeeceecffeeceecffeececfffeefeffffeefed
        ffffefffffffefffffffefffffffefffffffefffffffefffffffefffffffffcbbbbbbbddbbbdddcffffffffffffffffffffffffffffffffffffffffffffffffffffefffffffefffffffefffffffeffd
        ffffefffffffefffffffefffffffefffffffefffffffefffffffefffffffeffebebbbbbddbbdddbffffecffffffecffffffefffffffefffffffefffffffefffffffefffffffefffffffefffffffeffd
        fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffebbebbbbddbddddbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffd
        fefffffffefffffffeffffffffffffffffffffffffffffffffffffffffffffcebbbbebbbdbddddbcffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffefffffd
        feffeffffeffeffffeffeffffeffeffffeffeffffeffeffffeffeffffeffefcebbbbbbdbbbddddcffcffffffccffffffefffffffefffffffefffffffefffffffefffffffefffffffeffeffffeffeffd
        fffeeefffffeeffffffeeefffffeeffffffeeefffffeeffffffeeffffffeefcebbbbbbbbbbbdbdbfffeeefffffeeefffffeeefffffeeefffffeeefffffeeefffffeeefffffeeefffffeeefffffeeefd
        fffeeeeffffeeffffffeeeeffffeeffffffeeefffffefffffffeeefffffeffeeebbbbdbbbbbbddcffffeeefffffefffffffeeefffffefffffffeeefffffeffffffeeeeffffeeffffffeeeeffffeeffd
        fffeeeeffffeefeffffeeeeffffeefeffffeeeeffffeffeffffeeeeffffeffeebbbebbbbbbbbbbefffceeeefffeeffefffeeeeefffeefcefffeeeeefffeefeffffeeeeefffeefeffffeeeeffffeefed
        ffffefffffffefffffffefffffffefffffffefffffffefffffffefffffffffcbbbbbbebddddddbcffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffefffffffeffd
        ffffefffffffefffffffefffffffefffffffefffffffefffffffefffffffeffebebbbbbddddddbeffffeeffffffecffffffefffffffefffffffefffffffefffffffefffffffefffffffefffffffeffd
        fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffebbbbddddddbddbefffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffd
        fefffffffefffffffefffffffefffffffefffffffeffffffffffffffffffffcebbbddbbddbbddbefffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffefffffd
        feffeefffeffeffffeffeffffeffeffffeffeffffeffeffffeffeffffeffefcebbddddddbbddddcfecffefffecffefffecffefffefffefffefffefffefffefffeffeefffeffeefffeffeefffeffeefd
        fffeeefffffeeffffffeeffffffeeffffffeeffffffeeffffffeeffffffeefcbbdbbdbbdddbbdbcfffeeefffffeeefffffeeefffffeeefffffeeefffffeeefffffeeefffffeeefffffeeefffffeeefd
        ecceecececceecececceecececceecececceeeeeecceeeeeecceeeeeecceeeebdbddddbddbddddbeeceeeeeeeceeeeeeeceeeeeeeceeeeeeeceeeeeeeceeeececceeeececceecececceecececceeced
        `, img`
        bbbbdbbdbbbbdbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbddbdddddddddddddbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbdbbbbbbbdbbbbbbbdbbd
        ffffeffcffffeffcffffeffcffffeffcffffefffffffefffffffefffffffeffebbbbbbbdbbbbddbeffffefffffffefffffffefffffffefffffffeffffffcefcffffcefcffffcefcffffcffcffffeffe
        fffffefffffffefffffffefffffffefffffffefffffffefffffffefffffffefcbbbbbbbddbbd1ddcffffefffffffefffffffefffffffefffffffefffffffefffffffefffffffefffffffefffffffeff
        fffffefffffffefffffffefffffffefffffffefffffffefffffffcfffffffffcbbeebbbbddbddddeffffefffffffefffffffefffffffefffffffefffffffefffffffefffffffefffffffefffffffeff
        effffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcbbbebebbddbddddefffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        ffefffffffefffffffefffffffefffffffefffffffefffffffefffffffeffffcbbbbbbbbbdbddddefefffffffefffffffefffffffefffffffefffffffefffffffefffffffefffffffefffffffefffff
        ffcfeeffffcfeeffffcfeeffffffeeffffffeeffffffeeffffffeeffffffeefcbbbbbbbdbbbddbdcffffeeffffffeeffffffeefffffceefffffceefffffceefffffceefffcfeeffffcfeeefffcfeeff
        ffffeeffffffeeffffffeeffffffeeffffffeeffffffeeffffffeeffffffeefeeebbbbbbbbbbdddcfffeeefffffeeffffffeeefffffeeffffffeeefffffeeffffffeeefffffeeffffffeeefffffeeff
        ffffeeeeffffeffeffffeeeeffffeffeffffeeeeffffeffeffffeeeeffffeffeeebbbbdbbbbbbdbefffeeeeffffeeffffffeeeeffffeefeffffeeeeffffeefeffffeeeeffffeefeffffeeeeffffeffe
        ffffeefcffffeeffffffeeffffffefffffffeeffffffefffffffeeffffffeffebbbbbbbbddbbbbbeffffeeffffffefffffffefcfffffefffffffefcffffceffffffcefcffffceffffffcefcffffeefe
        fffffefffffffefffffffefffffffefffffffefffffffefffffffefffffffefcbbbbbbbd1dddddbcffffefffffffefffffffefffffffefffffffefffffffefffffffefffffffefffffffefffffffeff
        fffffefffffffefffffffefffffffefffffffefffffffcfffffffffffffffffcbbebbbbdddddddbeffffffffffffffffffffefffffffefffffffefffffffefffffffefffffffefffffffefffffffeff
        effffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcbbbbddbdddbbddbefffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        ffefffffffefffffffefffffffefffffffefffffffefffffffefffffffeffffcbbbdddbddbbdddbefffffffffefffffffefffffffefffffffefffffffefffffffefffffffefffffffefffffffefffff
        ffffeeffffffeeffffffeeffffffeeffffffeeffffffeeffffffeeffffffeefcbbddddbddbddddbcffffeeffffffeeffffffeefffffceefffffceefffffceefffffeeffffffeeffffffeeffffffeeff
        ffffeeffffffeeffffffeeffffffeeffffffeeffffffeeffffffeeffffffeefebbbbddbbddbbddbcfffeeefffffeeefffffeeefffffeecfffffeecfffffeeffffffeeffffffeeffffffeeffffffeefc
        ffffeffeffffeffeeeeffcefeeeffcefeeeffcefeeeffcefeecffeefeecffeeebbbbbbdbbbbbbbbccefffecfeefffecfeefffecfeefffecfeefffeffeefffeffeefffeffeefffefffffeffeffffeffe
        ffffceffffffeefee44efe4ce44efe4ce4eefeeee4eeceeee4eeceeee4effeecbbbbbbbdbbbbddbce4eceeee44eceeee44efe4ee44efe4ee44efe4ee44efe4ee44efe4ce44efe4fffffceffffffcefc
        fffffefffffffeff444ee4ee444eeeee444eeeee444eeeee444eeeee4eeeeeecbbbbbbbddbbd1ddece4eeeee44eeeeee44eeeeee44eeeeee44eeeeee44eeeee444eeeec444eeeeffffffefffffffeff
        fffffefffffffeffe2eeeeee42eeeeee4eeeeece4eeeeece4eeeeeceeeeeeefebbeebbbbddbddddeeeeeeece4eeeeeceeeeeeeceeeeeeece2eeeeefe2eeeeefe2eeeeefe2eeeeeffffffefffffffeff
        efefffffffefffffeeee4efeeeee4efeeeeeeefeeeeeeefeeeeeeefeefeeeffcbbbbbbbbddbddddceee4eeeeeee4eeeeeee4eeeeeee4eeeeeee4efeeeee4efeeeee4efeeeee4efeffffffffffefffff
        ffefffffffefffffeee4eefeeee4eefeeee4eeeeeee4eeeeeee4eeeeefceeffebbbbbbbbbdbddddecee4eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeffefffffffefffff
        ffffeeffffffeeff4eceeefe4eeeeefeeeeeeeceeeeeeeceeeeeeefeecfeeefebbbbbbbdbbbddbdecceeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeceeeeeeeceeefeeeceeefe4efeeefeffffeeefffffeeff
        ffffeeffffffeefe4eeefee24eeefee24eeefee44eeefee44eeefeeeeeeffecceebbbbbbbbbbddbeeeeffee4eeefeee4eeefeee4eeefeee4eeefeee4eeefeee4eeefeee4eeefeeeffffeeefffffeefc
        ffffeeeeffffeffeeeefffeeeeefffeeeeefffeeeeefffeeeeefffeeeeeffffceebbbbbbbbbbbdbeceeffeeeeeeffeeeeeeffeeeeeeffeeeeecffeeeeefffeeeeefffeeeeefffeeffffeeeeffffeffe
        ffffceffffffceffeeceefeceeceefeceeceefeceeceefeceeceefefeefeeffcbbbbbbbbddbbbbbefeeeeffeeeceefceeeceefceeefeefceeefeffceeefefefeeefefefeeefefeffffffeffffffcefc
        fffffefffffffefffefeefeffefeefeffeeeefeffeeeefeffeeeefeffeeeeffebbbbbbbd1dddddbcffeeeeffffeeeeffffeeeeffffeeeeffefe4eeffefe4eeffefe4ceffefe4feffffffefffffffeff
        fffffefffffffeffffe4eeeeffe4eeeeffe4eeeeffe4eeeeffeeeeecffeefffcbbebbbbdddddddbcffe4eeefffeeeeefffeeeeeffeeeeeeffeeeeeeffeeeeeeffeeeeeeffeeeeeefffffefffffffeff
        cfefffffffefffffffeeeeeeffeeeeeeffeeeeeeffeeeeeeffeeeeefffeeeefcbbbbddbdddbbddbcfeeeeeeffeeeeeeffeeeeeeffeeeeeeffeeeeeeffeeeeeeffeeeeeeffeeeeeeffefffffffefffff
        ffefffffffefffffffefffffffefffffffefffffffefffffffefffffffeffffebbbdddbddbbdddbcffffeffffefffffffefffffffefffffffefffffffefffffffefffffffefffffffefffffffefffff
        ffffeeffffffeeffffefffffffefffffffefffffffefffffffcffffffffffffebbddddbbdbddddbefffffffffffffffffefffffffefffffffefffffffefffffffefffffffefffffffffeeffffffeeff
        ffffeeffffffeeffcfcceccfcfccefffccceefffccceefffccceefffccceeceebbbbdbbbbbbbbbbeeccecffffccecffffccecffffccecffffccecffffccecffffccecffffccecffffffeeffffffeefe
        ffffeffeffffeffeecceecbceceebcceeceebcceeceebcceeceebcceecebbbbbbbbbbbbbbbbbbbbbbeebbcceecebbcceecebbcceecebbcceecebbcceecebbcceecebbcceecebbccffffeefeffffeffe
        fffffefffffffefcbbbbbbbddbbbdddbdbbbdddbdbbbdddbbbbbdddbbbbbddbbbbbbddbbbbbbddbbbbbbddbbbbbbddbbbbbdddbbbbbdddbbbbbdddbdbbbdddbdbbbdddbdbbbdddbfffffefffffffefc
        fffffefffffffeffbbebbbbbddbb1dddddbb1dddddbb1dbdddbb1ddddbbb1ddddbbd1ddddbbddddddbbddddddbbddddddbbddddddbbddddddbbddddddbbddddddbbddddddbbddbbfffffefffffffeff
        cffffeffffffffffbbeebbbbdddbddddddbbddddddbbdbbdddbbddddddbddbbdddbdddddddbddbbdddbdddddddbddbbdddbdddddddbddbbdddbdddddddbddbbdddbdddddddbddbbcffffffffffffeff
        cfefffffffefffffebbebebbbdbbddddddbbddddddbbddbdddbbddddddbbddbdddbddddddbbddbbddbbddddddbbddbbddbbddddddbbddbdddbbddddddbbddbdddbbddddddbbddbbefefffffffefffff
        ffefffffffefffffebbbbbbdbbdbdbdddbbbdbdbdbbbdbdbdbbbdbdbdbbbdbdbdbbbdbdbdbbbdddddbbbddbddbbdddbddbbdddbddbbdddbddbbdddbddbbdddbddbbdbdbddbbdbdbffefffffffefffff
        ffffeeffffffeeffbbbbbbbbdbbbdbddbdbbbbbbbdbbbbbbbdbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbdbbbbbbbdbbbbbbbdbbbbbbbdbbbbbbbdbbbbbbbdbbbbbbffffeeefffffeeff
        ffffeeefffffeefebebbbbdbbbbbbddbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbdbbbbbbbdbbbbbbbdbbbbbbbdbbbbdbbdbbbbbffffeeefffffeefe
        ffffeeeeffffeffebcbbebdbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbcfffeeeeffffeffe
        fffffefffffffeffbbbbbbbbdddbdbdbbbbbbbbbdddbdbbbbbbbbbbbdddbdbbbbbbbbbbbdddbbbbbbbbbbbbdddbdbbbbbbbbbbbdddbdbdbbbbbbbbbdddbdbdbbbdbbbdbdddbdbdbfffffefffffffeff
        fffffefffffffeffbbebbbbb1dddddbbbbbbbbbb1dddddbbbbbbbbbb1dddddbbbbbbbbbdddddddbbbbbbbbbdddddddbbbbbbbbbdddddddbbbbbbbbbdddddddbbbbbbbbbdddddddbfffffefffffffeff
        cfffffffffffffffebbedbdbdddbdddbbbbbdbdbdddbddbbbbbbdbbbdddbddbbbbbbdbbddddbddbbbbbbbbbdddbdddbbbbbbbdbdddbdddbbbbbbbdbdddbdddbbbbbdbdbdddbdddbcfffffffffffffff
        cfefffffffefffffedbbddbbddbbddbbdbbbddbbddbbddbbdbbbddbbddbbddbbdbbbddbdddbbddbbdbbbddbddbbbddbddbbbddbddbbbddbdbbbbddbddbbbddbdbbbbddbddbbdddbcfefffffffefffff
        ffeffeffffeffeffbbbddddbdbbddddbddbddddbdbbddddbddbdddbbdbbdddbdddbdddbddbbdddbdddddddbddbddddbddbddddbddbddddbddbddddbddbddddbddbddddbdbbddddbffeffeffffeffeff
        ffffeeffffffeeffbbdbddbbdbdbddbbdddbddbbdbdbddbbdddbddbbdbdbddbbdddbddbbddbbddbbddbbddbdddbbddbdddbbddbdddbbddbdddbbddbdbdbbddbdddbbddbdbdbbddbffffeeffffffeeff
        ffffeeffffffeefebbbbbbdbbdbbdbdbbbbbbbbcbbbbbbbcbbbbbbbcbbbbbbbcbbebbbbcbbebbbbebbcbbbbebbcbbbbebbcbbbbbbbcbbbbbbbcbbbbbbbcbbbbbbbbbbdbbdbbdbdbfeffeefffeffeeff
        ffffeffeffffeffebbbbbbdbbbbbbbbefcfccffccfffcffffcfccffccfffffffccfccffccfffffffccfccfcccfffffffccfccfcccffcffffccccffcccffcfffcbbbbbdbbbbbbbbbfeeffcefe4effcef
        fffffefffffffeffbbbdbbbddbbbdddbfefeeffeeffffffffeeeeffeefffffffceeeeffeefffffffceeeeffeefffffffeeeeefceefffffffeeeeefeeeffffffcbbdbbbddbbbdddbfe4efe4c444efe4c
        fffffefffffffeffbbebbbdbddbb1ddbfefffffffffffffffefffffffffffffffcfffffffffffffffcffffffffffffffcfffffffffffffffeffffffffffffffcbebbbdbbdbbddddcc4eeeef444eeeef
        efffffffffffffffebbebbbbdddbdddbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcbbebbbbdddbdddbfeee4efeeeee4efe
        cfefffffffefffffedbbbebbbdbb1ddbfefffefffefffffffefffefffefffffffefffefffeffffffcefffefffeffffffeeffceffeeffffffeeffeeffeefffffcbbbbebbbdbbddddcee44eeeeee44efe
        ffeffeffffeffeffbbbbdbbdbbdbdbdbfefffffffffffffffefffffffffffffffefffffffffffffffeffffffffffffffceffffffffffffffeefffffffffffffcbbbdbbdbbdbdbdbcff4eeffecfeeefc
        ffffeeffffffeeffbbbdbbbbdbbbdbbbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcbbdbbbbdbbbdbbdceceeefe4efeeefe
        ffffeeeeffffeffebebbbbdbbbdbbddcfefeeffefffffffffefeeffefffffffffefeeffeffffffffccceefceffffffffefeeefeeffffffffefeeefeefffffffcebbbbdbbbdbbddbefeeffe44eefffe4
        ffffeeeeffffeffebbbbebdbbbbbbbbefefeeffefffffffffefeeffefffffffffefeeffefffffffffcfeeffeffffffffeffeffffffffffffeffefffffffffffcbbbebdbbbbbbbbbefefefeeeeefefee
        fffffefffffffeffbdbdbbeb11dbdbdcfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcdbdbbebd1dbdbdbfefeefeffefeefef
        fffffefffffffeffbbebbbbb1dddddbefffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcbebbbbbddddbdbbffee4cefffee4fec
        efffffffffffffffebbedbdbdddbdddefee44ee4eee4eefffee44ee4eee4eeffcee44ee4eee4eeffeee44ee4eee4ecffeee44ee4eee4efffeee4eeeeeeeeeffcbbedbdbdddbdbdbffe44eeeffe4eeee
        cfefffffffefffffedbbbdbb1dbbbdbefeeeeeeeeeeeeefffeeeeeeeeeeeeefffeeeeeeeeeeeecffceeeeeeeeeeeefffeeeeeeeeeeeeefffeeeeeeeeeeeeeffcdbbbdbbddbbbdbbffeeeeefffefeeee
        ffeffeffffeffeffbbbddbdbdbbddbdefeeeeeeeeeeeeffffeeeeeeeeeeeeffffeeeeeeeeeeeeffffeeeeeeeeeeeeffffeeeeeeeeeeeefffeeeeeeeeeeeeeffcbbddbdbdbbddbdbffefffffffefffff
        ffffeeffffffeeffbbdbbdbbdbdbbdbefeeeeeeeeeeeeefffeeeeeeeeeeeecffceeeeeeeeeeeefffceeeeeeeeeeeefffeeeeeeeeeeeeefffeeeeeeeeeeeeeffcbdbbdbbdbdbbdbbefefffffffefffff
        ffffeffeffffeffebdbbdbdbbdbbdbdcffffffffffffffffffffffcffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcdbbdbdbbdbbdbdbeefeefffeffeeffc
        cfffeffeffffeffebbbbebdbbbbbbbbefffffffffffffffcbbbbebdbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbcfffffffffffffffcbbbebdbbbbbbbbbbbbbbbbbbbbbbbbb
        fffffefffffffeffbdbdbbbddbbb11dbfeeeeffeeffffffcbdbdbbbddbbb11dddbbd11dddbbd1ddddbbd1ddddbbd1ddddbbd1ddddbbd1dbceeeeefeeeffffffcdbdbbbddbbbd1dbdbbb11dbdbbb11db
        fffffefffffffeffbbeebbdbbdbb1dbbfefffffffffffffcbbebbbdbddbbddddddbdddddddbdddbdddbdddddddbddbddddbdddddddbddbdceffffffffffffffcbeebbdbbdbbddbdbdbb1dbdbdbb1dbd
        efffffffffffffffebbebbbbdbdbdddbffffffffffffffffbbbebbbbddddddddddddddddddbddbbdddbdddddddbddbbdddbdddddddbddbbcfffffffffffffffcbbebbbbdbdbdddbdbdbdbdbdbdb1bbb
        cfefffffffefffffedbbbebbbdbb1dbbfeeffefffeffffffbdbbbebbbdbbddddddbddddddbbddddddbbddddddbbddddddbbddddddbbddddceeffeeffeefffffcdbbbebbbdbbddbdbdbbddbdbdbb1dbd
        ffeffeffffeffeffbbbbdbbdbbdbdbdbfefffffffffffffcbbbbdbbdbbdbdbdddbbbbbbbdbbbbbbbdbbbbbbbdbbbbdbddbbdbdbddbbdbdbceffffffffffffffcbbbdbbdbbdbdbdbdbbbdbdbdbbbdbdb
        ffffeeffffffeeffbbbdbbbbdbbbdbbbfffffffffffffffcbbbdbbbbdbbbdbddbdbbbbbbbdbbbbbbbdbbbbbbbdbbbbbbddbbbbbbddbbbbbcfffffffffffffffcebdbbbbdbbbdbbdbdbbbbbbbdbbbbbb
        ffffeeeeffffeffebebbbbdbbbdbbddefefeeffeefffffffeebbbbdbbbdbbddbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbdbbdbbbbbcefeeefeefffffffcebbbbdbbbdbbddbbbdbbbbdbbdbbbbd
        ffffeeeeffffeffebbbbebbbbbbbbbbefefffffffffffffcbbbbebbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbceffffffffffffffcbbbebbbbbbbbbbbbbbbbbbbbbbbbbbb
        fffffefffffffeffbdbdbbeb11dddddcfffffffffffffffcbbbbbbeb1ddddddbbbbbbbbd1dddddbbbbbbbbbd1dddddbbbbbbbdbd1dddddbcfffffffffffffffcdbdbbebd1dbdbdbbbdbbbdb11dbdbdb
        fffffefffffffeffbbebbbbb1dbdddbcfffccffcfffcffffbbebbbbbddddddbbbbbbbbbdddddddbbbbbbbbbdddddddbbbbbbbbbdddddddbcfffcfffffffffffcbeebbbbddbdbdbbbbbbbbbb1dbdbdbb
        efffffffffffffffebbbdbdbdddbdddefee44ee4eee4eeffbbbbdddbdddbdddbbbbbddbdddbbddbbbbbbddbdddbdddbbbbbdddbdddbdddbceee44ee4eee4effcbbedbdbdddbdbdbbbbbdbdbdbdbdbdb
        ffefffffffefffffedbbbdbb1dbbbdbefeeeeeeeeeeeeeffbdbbddbbddbbddbddbbbddbddbbbddbddbbbddbddbbbddbddbbbddbddbbbddbceeeeeeeeeeeeeffcbbbbdbbddbbbdbbdbbbbdbb1dbbbdbb
        ffeffeffffeffeffbbbddbdbdbbddddcfeeeeeeeeeeeeffcbbdddddbdbddddddddddddbddbddddbdddddddbddbddddbdddddddbdbbddddbceeeeeeeeeeeeeffcbbddddbdbbddddbddbddbdbdbbddbdb
        ffffeeffffffeeffbbdbbdbbdddbbdbefeeefeeefeeefcfcbbdbddbbddbbddbbddbbddbbddbbddbbddbbddbbddbbddbbddbbddbbddbbddbceeefeeefeeefeffcbdbbddbdbdbbdbbdbdbbdbbdbdbbdbb
        ffffeffeffffeffebbbbbbdbbdbbdbdcfffffffffffffffcbbbbbbdbbbbbdbbbddbdbbbbbdbddddbbbbbbbbbbbbbbbbbbbbbbdbbbbbdbdbcfffffffffffffffcbbbbbdbbdbbdbdbebcebebeebcebebb
        ffffeefeffffeffebbbbebdbbbbbbbbcfcfffffffffffffcbbbbebdbbbbbbbbbdddbccccbbbdddddbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbcfffffffffffffffcbbbebbbbbbbbbbbffffeefeffffeefe
        fffffefffffffeffbdbdbbbddbbb11dbfefeeffeeffffffcbbbbbbbddbbb1ddbdbefffffffcbbddddbbd1ddddbbd1ddddbbd1ddddbbd1dbceeeeefeeeffffffcbbbbbbddbbbd1dbfffffefffffffeff
        fffffefffffffeffbbeebbdbbdbbdddbfcffffffffffffffbbeebbbbddbbddddbecfffffffffcbddddbdddddddbddbbdddbdddddddbddbbccffffffffffffffcbeebbdbbdbbddddcffffefffffffeff
        efffffffffffffffebbebebbdddbdddbffffffffffffffffbbbebbbbddbddddbbebcfffffffffcbdddbdddddddbddbbdddbdddddddbddbbcfffffffffffffffcbbebebbdddbdddbefffffffffffffff
        ffefffffffefffffedbbbebbbdbbdddbfefffefffeffffffbbbbbebbbdbbdddbbbbcffffffffffcddbbddddddbbddddddbbddddddbbddddceeffeeffeefffffcbbbbebbbdbbddddcfefffffffefffff
        ffefceffffefceffbbbbdbbdbbdbdbdbfefffffffffffffcbbbbbbbdbbbbdbdbbddcfeecffffffcbdbbbbbbbdbbbbbbbdbbbbbbbdbbbbbbccffffffffffffffcbbbdbbddbdbdbdbffeffeffffeffeff
        ffffeeffffffeeffbebdbbbbdbbbdddbffffffffffffffffeebbbbbbbbbbdddbbddcfebcfffffffcbdbbbbbbbdbbbbbbbdbbbbbbbdbbbbbcfffcfffffffffffcebbbbbbdbbbddddffffeeefffffeeff
        ffffeeeeffffeffebebbebdbbbdbbddefefeeffeffffffffeebbbbdbbbbbbdbbbddcfebcfeecfffcbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbcefeeefeefffffffcebbebdbbbdbbddbffffeeeeffffeffe
        ffffeefeffffeffebbbbebbbddbbbbbefefffffffffffffcbbbbebbbddbbbbbbbddcfebccebcfffcbbbbbbbbddbbbbbbbbbbbbbbddbbbbbceffffffffffffffcbbbbbbbbddbbbbbffffeefeffffeefe
        fffffefffffffeffbbbbbbeb11dddddefffffffffffffffcbbbbbbbb1dddddbbbddcfebccebcfcccbbbbbbbd1dddddbbbbbbbbbd1dddddbcfffffffffffffffcbbbbbebd1dddddbfffffefffffffeff
        fffffefffffffeffbbeebbbbddddddbefefeecfeecfeefffbbebbbbbddddddbbbdbcfebccebcfcccbbbbbbbdddddddbbbbbbbbbdddddddbccfeeefeeefeeeffcbeebbbbdddddddbfffffefffffffeff
        efffffffffffffffebbbdddbdddbdddefee44ee4eee4eeffbbbbddbbddbbddbbbecffebcfebcffcbbbbbddbdddbbddbbbbbbddbdddbbddbceee4eeeeeeeeeffcbbbbddbdddbdddbefffffffffffffff
        ffefffffffefffffebbdddbbddbdddbefeeeeeeeeeeeeeffbbbdddbbdbbdddbbbcfffcecfeecfcbddbbdddbddbbdddbddbbdddbddbbdddbceeeeeeeeeeeeeffcbbbdddbddbbdddbffefffffffefffff
        ffcfeeffffcfeeffbbdddddbdbddddbefeeeeeeeeeeeeefcbbddddbbdbddddbddbeccccffccccbbdddddddbddbddddbdddddddbdbbddddbceeeeeeeeeeeeeffcbbddddbdbdddddbffcfeeffffcfeeff
        ffffeeffffffeefcbdbbdddbddbbddbefecffccffccffffcbdbbddbbddbbddbbdbbbbcccccbbddbbddbbddbbddbbddbbddbbddbbddbbddbccccffccffccffffcbdbbddbbddbdddbffffeeffffffeeff
        ffffeffeffffeffebbbbbbdbbbbbbbbcfffffffffffffffcbbbbbbdbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbcfffffffffffffffcbbbbbdbbbbbbbdbffffeefeffffeffe
        ffffceffffffcffebbbbebbddbbbddbcfefeeffecffffffcbbbbbbbdbbbbddbbbbbbddbbbbbbddbbbbbbddbbbbbbddbbbbbbddbbbbbbddbccfcefffefffffffcbbbbbbddbbbdddbffffceffffffcefc
        fffffefffffffeffbbebbbbdddbb1ddbfefeeffeeffffffcbbbbbbbddbbb1ddddbbd1ddddbbd1ddddbbd1ddddbbd1ddddbbd1ddddbbd1ddceeeeefeeeffffffcbbbbbbbddbbd1ddfffffefffffffeff
        fffffefffffffeffbbeebbbbdddbdddbffffffffffffffffbbeebbbbddbdddddddbdddddddbddbbdddbdddddddbddbbdddbdddddddbddbbcfffffffffffffffcbeebbbbdddbdddbcffffefffffffeff
        efffffffffffffffedbebebbddbbdddbfefffefffcffffffbbbebebbddbdddddddbdddddddbddbbdddbdddddddbddbbdddbdddddddbddbbccffffffffffffffcbbebebbbddbddddefffffffffffffff
        ffefffffffefffffebbbbbbdbbdbdddbfefffefffeffffffbbbbbbbbbdbddddddbbbdddddbbddddddbbddddddbbddddddbbddddddbbdddbceeffeeffeefffffcbbebbbdbbdbdddbffefffffffefffff
        ffffeeffffffeeffbbbbbbbbdbbbdbdbfffffffffffffffcbbbbbbbdbbbbdbdddbbbbbbbdbbbbbbbdbbbbbbbdbbbbbbbdbbbbbbbdbbbbbbcfffffffffffffffcbbbbbbbdbbbdbbdffffeeefffffeeff
        ffffeeffffffeefcbebbbbdbbbdbbddbfcfeeffeffffffffeebbbbbbbbbbdddbbdbbbbbbbdbbbbbbbdbbbbbbbdbbbbbbbdbbbbbbbdbbbbbccfceffcffffffffcebbbbdbbbdbbddbffffeeefffffeefc
        ffffeeeeffffeffebebbebdbbbbbbbbefefeeffeffffffffeebbebdbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbcefeeefeefffffffcebbebdbbbbbbbbbffffeeeeffffeffe
        fffffefffffffffcbbbdbbbbdddbdbdefffffffffffffffcbbbbbbbbdddbbbbbbbbbbbbbddbbbbbbbbbbbbbbddbbbbbbbbbbbbbdddbdbdbcfffffffffffffffcbbdbbbbdddbdbdbfffffefffffffefc
        fffffefffffffeffbbebbbbb1dddddbcfffffffffffffffcbbbbbbbb1dddddbbbbbbbbbd1dddddbbbbbbbbbd1dddddbbbbbbbbbd1dddddbcfffffffffffffffcbebbbbbd1dddddbfffffefffffffeff
        cffffefffffffeffbbeedbdbdddbdddcfeeeeeeeeeeeeeffbbebbbbbddddddbbbbbbbbbdddddddbbbbbbbbbdddddddbbbbbbbdbdddddddbceeeeeeeeeeeeeffcbbebbdbdddbdddbcffffefffffffeff
        efffffffffffffffedbbbdbb1dbbddbefee44eeeeeeeeeffbbbbddbbddbbddbbdbbbddbdddbbddbbbbbbddbdddbbddbbbbbbddbdddbbddbceee4eeeeeeeeeffcbbbbdbbddbbbdbbefffffffffffffff
        ffefffffffefffffebbddddbdbbddddefeeeeeeeeeeeeeffbbbddddbdbbdddbdddbdddbddbbdddbddbbdddbddbbdddbddbddddbddbddddbceeeeeeeeeeeeeffcbbddddbdbbddddbffefffffffefffff
        ffffeeffffffeeffbbdbbdbbdbdbddbefeeeeeeeeeeeeefcbbdbddbbdbdbddbbdddbddbddbdbddbddddbddbddddbddbddddbddbdbdbbddbceeeeeeeeeeeeeffcbdbbdbbdbdbbdbbffffeeffffffeeff
        ffffeeffffffeefcbdbbdbdbbdbbdbdefffffffffffffffcbdbbdbbbbdbbdbbbbdbbdddbddbbddbbbbbbddbbbbbbbdbbdbbbbdbbdbbbbdbcfffffffffffffffebbbdbdbbdbbdbdbffffeeffffffeefc
        ffffeffeffffeffeecceeeeeecceeeeeffffeffeffffeffeecceeeeeecceeeeebbbbbbdbbbbbbbbeccceeeeeccceeeeeccceeeeecceeeceefffeffeffffeffeecceeeceecceeeceffffeefeffffeefe
        fffffefffffffffffffffffffffffffffffffffffffffffffffffffffffffffebbbbbbbddbbbddbcffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffefffffffffffffffeff
        fffffefffffffefffffffefffffffefffffffeffffffeeffffffeeffffffeefcbbbbbbdbdbbd1ddcffffecffffffefffffffefffffffefffffffefffffffefffffffefffffffefffffffefffffffeff
        cffffefffffffffffffffffffffffffffffffffffffffffffffffffffffffffcbbeebbbbddbddddeffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffefffffffeff
        effffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcbbbbeebbddbddddbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffc
        ffefffffffefffffffefffffffefffffffeffffffeeffffffeeffffffeeffffcbbbbbbbdbddddddcfecffffffecffffffefffffffefffffffefffffffefffffffefffffffefffffffefffffffefffff
        ffffeeffffffeeffffffeeffffffeeffffffeefffffeeefffffeeefffffeeefcbbbdbbbdbbbddbdcfffeeefffffeeefffffeeefffffeeefffffeeefffffeeefffffeeefffffeeefffffeeefffffeeff
        ffffeeffffffeeffffffeeffffffefffffffeeffffffefffffffeeffffffeffeeebbbbdbbbbbdddcffffeeffffffefffffffeeffffffefffffffeefffffeeffffffeeefffffeeffffffeeefffffeefe
        cfffeeeeffffeffeffffeeeeffffeffefffeeeeefffeeffefffeeeeefffeeffeeebeebdbbbbbbbbefffeeeeefffeefeefffeeeeefffeefeefffeeeeefffeefeffffeeeeffffeefeffffeeeeffffeefe
        fffffefffffffffffffffefffffffffffffffffffffffffffffffffffffffffcbbbbbbbbddddddbcffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffeff
        fffffefffffffefffffffeffffffeeffffffeeffffffeeffffffeeffffffeefcbbebbbbd1dddddbcffffecffffffefffffffefffffffefffffffefffffffefffffffefffffffefffffffefffffffeff
        effffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcbbebddddddddddbefffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        effffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffebdbbddbd1dbbddbeffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffc
        ffefffffffefffffffeffffffeeffffffeeffffffeeffffffeeffffffeeffffcbbbddddddbddddbcfecffffffecffffffefffffffefffffffefffffffefffffffefffffffefffffffefffffffefffff
        ffffeeffffffeefffffeeefffffeeefffffeeefffffeeefffffeeefffffeeefcbbdbddbddddbddbcfffeeefffffeeefffffeeefffffeeefffffeeefffffeeefffffeeefffffeeefffffeeefffffeeff
        feffeefcfcffeefcfcffeefcfcffeefcffffeeffffffeeffffffecffffffecfebdbddddbddbddddcffffeffffffceffffffceffffffceffffffcefcffffeefcfcffeefcfcffeefcfcffeefcfcffeefe
        ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd1111111111111111ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd1
        `, img`
        bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbd
        fffcefcffffcfffffffcfffffffcfffffffcfffffffcfffffffcfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffefffffffffffffffffffffffefcd
        ffffefffffffefffffffefffffffefffffffefffffffefffffffefffffffefffffffefffffffefffffffefffffffeffffffffffffffffffffffffffffffefffffffefffffffefffffffefffffffeffb
        ffffefffffffefffffffefffffffefffffffefffffffefffffffeffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffefffffffefffffffefffffffefffffffefffffffeffb
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffb
        fefffffffefffffffefffffffefffffffefffffffefffffffefffffffefffffffefffffffefffffffeffffffffffffffffffffffffffffffefffffffefffffffefffffffefffffffefffffffefffffb
        fffceefffffceefffffceefffffceffffffeeffffffeeffffffeeffffffeeffffffeeffffffeeffffffeeffffffeeffffffeeffffffeeffffffeeffffffeeffffffeeffffffeeffffffeeffffffeefb
        fffeeefffffeeffffffeeefffffeeffffffeeefffffeeffffffeeffffffeeffffffeeffffffeeffffffeeffffffeeffffffeeffffffeefffffeeefffffeeefffffeeefffffeeffffffeeefffffeeffb
        fffeefeffffeefeffffeeeeffffeefeffffeeeeffffeffeffffeeeeffffefffffffeeeeffffefffffffeeeeffffefffffffeeefffffefffffffeeeffffeeffffffeeeeffffeefcffffeeeeffffeefed
        ffffefefffffeffffffceffffffceffffffcefffffffffffffffefffffffffffffffeffffffffffffffeeffffffefffffffefffffffefffffffefffffffefffffffefefffffefffffffefefffffefcb
        ffffefffffffefffffffefffffffefffffffefffffffefffffffefffffffefffffffefffffffefffffffeffffffffffffffffffffffffffffffffffffffefffffffefffffffefffffffefffffffeffb
        ffffefffffffefffffffefffffffefffffffefffffffeffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffefffffffefffffffefffffffefffffffeffb
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffb
        fefffffffefffffffefffffffefffffffefffffffefffffffefffffffefffffffefffffffeffffffffffffffffffffffffffffffffffffffffffffffefffffffefffffffefffffffefffffffefffffb
        fffceefffffceefffffceffffffceffffffeeffffffeeffffffeeffffffeeffffffeeffffffeeffffffeeffffffeeffffffeeffffffeeffffffeeffffffeeffffffeeffffffeeffffffeeffffffeefb
        fffeeffffffeeffffffeeffffffeeffffffeeffffffeeffffffeeffffffeeffffffeeffffffeeffffffeeffffffeeffffffeeffffffeeffffffeefffffeeefffffeeefffffeeefffffeeffffffeeffb
        fffeefeffffeefeeeefffeffeefffeffeeffcefceeffcefceecceeceeecceeceeecceeceeecceeceeecceeceeccceefeecffecfeecffecfeefffecfeefffecfeefffecfeefffecffffeefeffffeefed
        ffffefffffffeffe44efe4ee44efeeee44efeeee44efeeebddbbbbbbddbbbbbbdbbbbbbbdbbbbbbbdbbbbbbbdbbbbbee4eeeeeee4eeeeeee4eeeeeee4eceeeee4eceeee44ece4efffffefffffffefcb
        ffffefffffffeffe44eeeeee44eeeeee44eeeeee44eeeeed111111111111111111111111111111111111111111111be444eeeee444eeeee444eeeee44eeeeee44eeeeee44eeeeefffffefffffffeffb
        ffffefffffffeffe4eeeeece2eeeeeee2eeeeeee2eeeeeed1111111111111111ddd11111111111111111111111111beeeeeeeceeeeeeeceeeeeeeceeeeeeeceeeeeeefeeeeeeeffffffefffffffeffb
        fffffffffffffffeeee4efeeeee4efeeeee4efeeeeeeeeed11dbdddbdd1dd11dbbbddbd1ddd11ddddbbddd11ddbd1beeeeeeeeeeeeeeeeeeeeeeeeeeee4eeeeeee4eeeeeee4eeeefffffffffffffffb
        fefffffffefffffeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeed11dcbbbcbbbbbd1bccbbbbddbbbddbbbdccbbbddbbbd1beeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeffefffffffefffffb
        fffceefffffceffeeceeeeeeeeeeeeeeeeeeeeeeeeeeeeed11dccbccbccbbd1bccbbbbbbbccbbbbbdccbbbdbbbbd1beeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeefffffeefffffceefb
        fffeeefffffeeffeeeefeee4eeefeee4eeefeee4eeefee4d11dcbdbcbcbd111bcbbbbbbbdbbbbbbd1bbdbbdbbbbd1d44eeeeeee4eeeeee44eefeee4eeefeee4eeefeee4eeefeeeffffeeefffffeeffb
        fffeefeffffeefeeeefffeeeeefffeeeeefffeeeeefffeed11dcd1dcbcd111dbcbbbbbbbdbcddbbbdbbddbbccbdd1deeeefffeeeeefffeeeeeffeeeeeeffeeeeeeffeeeeeeffeecfffeeeeffffeefed
        ffffefffffffeffeeefeffceeeceffceeeeeffceeeeeffed11dbd1dbbbd11ddbccbbbbdbbcbbbbbddbbdddbcbbd11beeeeeeffeeeeeeffeeeceeffeeeceeffeeefeeffeeefeffffffffefffffffeffb
        ffffefffffffefffefeeeeffefeeeeffeeeeeeffeeeeeeed11ddd1ddddd11dddbbddddddbbddbbd11dd1dbbbddd11bcffeeeeffffeeeeffffeeeeffffeeeeffffeeeeffffeeeeffffffefffffffeffb
        ffffeffffffffffffeeeeeeffeeeeeeffeeeeeeffeeeeeed111111111111111111111111111111111111dbbd11111beffeeeeefffeeeeefffeeeeefffeeeeefffeeeeefffeeeeeffffffffffffffffb
        fffffffffffffffffeeeeeeffeeeeeeffeeeeeeffeeeeeed111111111111111111111111111111111111111111111beffeeeeeffeeeeeeffeeeeeeffeeeeeeffeeeeeeffeeeeeeffffffffffffffffb
        fefffffffefffffffefffffffefffffffefffffffeffffcbdddddddddddddddddddddddddddddddddddddddddddddbffffffffffefffffffefffffffefffffffefffffffefffffffefffffffefffffb
        fffeeefffffeeffffefffffffefffffffefffffffcfffffceeeeeecceeeeeecceeeeeecceeeeeecceeeeeecceeeeecffffffffffffffffffffffffffffffffffffffffffefffffffffceefffffeeefb
        fffeeffffffeeffffcceccfffccecffffffffffffffffffffcccccfffccefffffffffffffffffffffccccfffccecffffffffffffffffffffcceccfffccecffffccecffffccecffffffeeffffffeeffb
        fffeefeffffeefeecceeebbeeeebbccffffffffffffffffeceeeebbeeeebeccffffffffffffffffeceeecbbeeeebcccfffffffffffffffceceeecbbecebbcceecebbcceecebbcccfffeefeffffeefed
        ffffefffffffeffebbbbbbddbbbdddbceceeffcefffffffcbbbbbbddbbbdddcfffffffffffffffcbbbbbbbdbbbbddbcceceeffeeffffffcbbbbbbbdbbbbddbbbbbbddbbbbbbddbcffffefffffffeffb
        ffffefffffffeffcbbbbbbbddbbdddbcefeefffefffffffcbbbbbbbddbbdddbcffefe22effefffcbbbbbbbbdbbddddceefeeffeeffffffcbbbbbbbddbbddddddbbddddddbbddddcffffefffffffeffb
        fffffffffffffffebbebbbbbddbdddbcfffffffffffffffcbeebbbbbdbbdddbceeeee444eeeeefcebeebbbbddbddddccffffffffffffffcbbeebbbbddbdddddddbdddddddbddbbefffffffffffffffb
        fffffffffffffffebbebebbbddbdddbcefffcffffffffffcbbbbbbbbdbbdddbeee4e44444eeeeefbbbbbbbbbdbddddccefffffffffffffcbbbbbbbbddbddddddbbddddddbbddbbefffffffffffffffb
        fefffffffefffffebbbbbbbbbbbdddbceefffffffffffffcbbbbbbbbbbbdddbe4e4e44444e4e4ecebbbbbbbbbbddddccefffffffffffffcbbbbbbbbbbbddddddbbdddbddbbdddbcfefffffffefffffb
        fffeeefffffeeffebbbbbbbbbbbdbdbcfffffffffffffffcbbbbbbbbbbbdbdbeee4e44444e4eeecebbbbbbbbbbbdbdccffffffffffffffcebbbbbbbbbbddbdbdbbbbbbbdbbbbbbcfffeeefffffeeefb
        fffeeefffffeeffeebbbbdbbbbbbddbccfeeffcffffffffcebbbbdbbbbbbddbeee4ee44eee4eefceebbbbbbbbbbbdbccffeeffffffffffceebbbbbbbbbbbdbbbbbbbbbbbbbbbbbcfffeeefffffeeffb
        fffeefeffffeefeeebbebdbbbbbbbbbcefeefffefffffffcebbbbbbbbbbbbbceeeeefeecfeeeefccbbbbbbbbbbbbbbcccfeeffefffffffccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbefffeeeeffffeefed
        ffffefffffffeffebbbbbbbdddbdbbbffffffffffffffffcbbbbbbbdddbbbbcceeefceeefeeeefcbbbbbbbbdddbbbbcfffffffffffffffcbbbbbbbbddbbbbbbbbbbbbbdddbdbdbcffffefffffffeffb
        ffffefffffffeffcbbbbbbbddddddbbffffffffffffffffcbbbbbbbddddddbcffeefceeeffefffcbbbbbbbbddddddbcfffffffffffffffcbbbbbbbdddddddbbbbbbbbbdddddddbcffffefffffffeffb
        fffffffffffffffebbebbbbdddbdddbceeeeeeeeeeeeeffcbbbbbbbdddbddbcceeeeceeefeeeefcebebbbbdddddddbcceeeeeeeeeeeeffcbbebbbbdddbdddbbbbbbbbbdddbdddbefffffffffffffffb
        fffffffffffffffebbbbddbddbbbdbbceeeeeeeeeeeeeffcbbbbdbbddbbddbce442eeeefee222ffbbbbddbdddbbddbceeeeeeeeeeeeeefcbbbbddbddbbbddbddbbbddbddbbbddbefffffffffffffffb
        fefffffffefffffebbddddbddbddddbfeeeeeeeeeeeeeffcbbddddbdbbdddbcc4422eeeee2222fcebbdddbddbbdddbcceeeeeeeeeeeeffcbbbdddbddbddddbdddddddbddbddddbcfefffffffefffffb
        fffeeefffffeeffebdbbddbdbdbbdbbceeeeeeeeeeeeeffcbdbddbbdddbddbcfeeeeeeeeeeeeffcbbbbddbbddbbddbcceeeeeeeeeeeeffcbbbbddbdddbbddbdddbbddbdddbbddbcfffeeefffffeeefb
        fffeeffffffeefcebbbbbdbbdbbbbbbffffffffffffffffcbbbbbdbbdbbbbbccffffffffffffffcbbbbbbbbbbbbbbbcfffffffffffffffcbbbbbdbbbbbbbdbbbbbbbdbbbbbbbdbcfffeeffffffeeffb
        fffeefeffffeefeebbbbbdbbbbbbbbbffffffffffffffffcbbbbbdbbbbbbbbbbeeebbbbbeeebbbbbbbbbbbbbbbbbbbcfffffffffffffffcbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbefffeefeffffeefed
        ffffefffffffeffebbbbbbddbbbdddbceeeeffeefffffffcbbbbbbddbbbdddbdbbbdddddbbbddddbbbbddddbbbbdddceeeeeffeeffffffcbbbbbbbdbbbdddddbbbdddbdbbbdddbcffffffffffffeffb
        ffffefffffffeffcbebbbbbbdbbdddbceffffffffffffffcbebbbbbbdbbddddddbbddddddbbddddddbbddddddbdddbcccfffffffffffffcbbbbbbbbdbbddddddbbddddddbbddddcffffefffffffeffb
        fffffffffffffffebbebbbbdddbdddbcfffffffffffffffcbbebbbbdddbddddddbbddddddbddbbbddbdddddddbddbbcfffffffffffffffcbbeebbbbddbdddddddbdddddddbddbbefffffffffffffffb
        fffffffffffffffebbbbebbbdbbdddbceeffeeffeefffffcbbbbebbbdbbddddddbbddddddbbddddddbbddddddbddddceefffefffefffffcbbbbbbbbbdbddddddbbddddddbbddbdefffffffffffffffb
        fefffffffefffffebbbbbbdbbdbdbdbceffffffffffffffcbbbbbbdbbbbdddddbbbdbbbdbbbdbbbdbbbdbbbdbbbddbccefffffffffffffcbbbbbbbbbbbddddddbbdbdbddbbdbdbcfefffffffefffffb
        fffeeefffffeeefebbbbbbbdbbbdbbbcfffffffffffffffebbbbbbbbbbbdbddbdbbbbbbbdbbbbbbbdbbbbbbbdbbbbbcfffffffffffffffcebbbbbbbbbbddbdbdbbbbbbbdbbbbbbcfffeeefffffeeefb
        fffeeeeffffeefceebbbbdbbbdbbddbcefeeffeefffffffcebbbbdbbbbbbddbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbcecceeffefffffffceebbbdbbbbbbbdbbbbbbbbbbbdbbbbbcfffeeeeffffeeffb
        fffeeeeffffeefeebbbebbbbbbbbbbbceffefffffffffffcbbbebbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbccfffeffffffffffccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbefffeeeeffffeefed
        ffffefffffffeffebbbbbebd1dbdbdbffffffffffffffffebbbbbebddddddbbbbbbbbbdddddddbbbbbbbbbdddddddbcfffffffffffffffcbbbbbebdddddddbbbbbbbbbdddddbdbcfffffffffffffffb
        ffffefffffffeffcbebbbbbddddddbbffffffffffffffffcbebbbbbddddddbbbbbbbbbbddddddbbbbbbbbbdddddddbcfffffffffffffffcbeebbbbdddddddbbbbbbbbbdddddddbcffffefffffffeffb
        fffffffffffffffebbebbdbdddbdddbceee4eeeeeeeeeffcbbbbddbdddbdddbbbbbddbddddbddbbbbbbddbdddbbddbceee44eeeeeeeeefcbbebbdbdddbdddbbbbbbbdbdddbdddbefffffffffffffffb
        fffffffffffffffebbbbdbbddbbbdbeceeeeeeeeeeeeeffcbbbbdbbddbbbdbbdbbbbdbbddbbddbbdbbbddbdddbbddbcceeeeeeeeeeeeefcbbbbddbddbbbddbddbbbddbddbbbddbefffffffffffffffb
        feffeffffeffeffcbbddddbdbbddddbfeeeeeeeeeeeeeffcbbddddbdbbddddddddddddddbbdddddddddddbddbddddbcceeeeeeeeeeeeffcbbddddbddbddddbdddddddbdbbddddbcfefffffffeffeefb
        fffeeefffffeeefebdbbdbbdddbbdbeceeeeeeeeeeeeeffcbdbbdbbdddbbdbbdddbbdbbdddbbdbbdddbbdbbddbbddbcceeeeeeeeeeeeffcbdbbddbbddbbddbdddbbddbdddbbddbcfffeeefffffeeefb
        fffeeffffffeefcebbbbbdbbdbbdbdbffffffffffffffffcbbbbbbbbbbbbbbbbbbbbbdbbbbbbbbbbbcbbbbcbbcbbbbcfffffffffffffffcbbbbbdbbbbbbbdbbbbbdbdbbdbbdbdbcffffefffffffefcd
        fffeefeefffeefeebbbebdbbbbbbbbeffffffffffffffffffffffffffffffffcbbbebbbbbbbbbbcfffffffffffffffffffffffffffffffccbbbebbbbbbbbbbbbbbbbbbbbbbbbbbefffeefeefffeefed
        fffffffffffffffcdbdbbbddbbbd1dbceeeeefeeffffffffeeeeffeefffffffbbbbbbbddbbbd1dceeeeeffeefffffffceeeefceeffffffcbbbbbbbddbbd1ddddbbd1ddddbbd1dbcfffffffffffffffb
        ffffefffffffeffcbeebbdbbdbbdddbccfffffffffffffffcffffffffffffffebeebbbbbdbbdddbcffffffffffffffffffffffffffffffcbeebbbbbddbdddddddbdddddddbddbdcffffefffffffeffb
        fffffffffffffffebbebbbbdddbdddbffffffffffffffffffffffffffffffffcbbebbbbdddddddcfffffffffffffffffffffffffffffffcbbeebbbbddbdddddddbdddddddbddbbefffffffffffffffb
        fffffffffffffffebbbbebbbdbbdddbceeffeeffeeffffffeeffeeffeefffffcbbbbebbbdbbdddbeeeffeeffeeffffffeefceefceeffffcbbbbbebbbdbddddddbbddddddbbddddefffffffffffffffb
        feffeefffeffeffcbbbdbbdbbdbdbdbcefffffffffffffffeffffffffffffffebbbbbbdbbbddbdbcefffffffffffffffefffffffffffffcbbbbbbbdbbbddddddbbbbdbddbbbbdbcfeffeefffeffeefb
        fffeeefffffeeffebbdbbbbdbbbdbbbcfffffffffffffffffffffffffffffffebbbbbbbbbbbdbbbfffffffffffffffffffffffffffffffcebbbbbbbbbbbdbdbddbbbbbbdbbbbbbcfffeeefffffeeefb
        fffeeeeffffeefeeeebbbdbbbdbbddbcefeeefeeffffffffefeeffeefffffffcebbbbdbbbbbbddcceceeffeeffffffffcceefceeffffffceebbbdbbbbbbbdbbbbbbbbbbbdbbbbbcffffeeefffffefcd
        fffeefeffffeefeebbbebbbbbbbbbbbcefffffffffffffffeffffffffffffffcbbbebbbbbbbbbbccffffffffffffffffffffffffffffffcebbbbbbbbbbbbbbbbbbbbbbbbbbbbbbefffeeeeffffeefed
        ffffefffffffeffcdbbbbebd1dddddbffffffffffffffffffffffffffffffffbbbbbbebddddddbcfffffffffffffffffffffffffffffffcbbbbbebd1dddddbbbbbbbbbd1dddddbcfffffffffffffffb
        ffffefffffffeffcbeebbbbddddddbbffffcfffffffffffffffcfffffffffffebebbbbbddddddbcfffffffffffffffffffffffffffffffcbeebbbbdddddddbbbbbbbbbdddddddbcffffefffffffeffb
        fffffffffffffffebbebddbdddbdddbceee4eeeeeeeeefffee44eeeeeeeeeffcbbbbddddddbddbceee44eeeeeeeeeffcee44eeeeeeeeefcbbebbdbdddbdddbbbbbbddbdddbdddbefffffffffffffffb
        fefffffffefffffebbbbdbbddbbbdbbceeeeeeeeeeeeefffeeeeeeeeeeeeeffcbbbddbbddbbddbcceeeeeeeeeeeeefffeeeeeeeeeeeecfcbbbbddbddbbbddbddbbbddbddbbbddbefffffffffefffffb
        feffeefffeffeffcbbddddbdbbddddbfeeeeeeeeeeeeefffeeeeeeeeeeeefffcbbdddbddbbdddbcceeeeeeeeeeeeffffeeeeeeeeeeeeffcbbddddbddbddddbdddddddbdbbddddbcfeffeefffeffeefb
        fffeeffffffeeffebdbbdbbdddbbdbbceeeeeeeeeeeecfffeeeeeeeeeeeecffbbbbbdbbddbbbdbcceeeeeeeeeeeefffceeeeeeeeeeeeffcbdbbddbbddbbddbbddbbddbbddbbddbcfffeeefffffeeffb
        fffeeffffffeefeebbbbbdbbdbbdbdbccccccccccccccccccccccccccccccccbbbbbbbbbbbbbbbeccccccccccccccccccccccccccccccccbbbbbbbbbbbbbdbbbbbbbdbbbbbbbdbcffffeffffffeefcd
        fffeefcffffeefeebbbbbbbbbbbbdbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbefffeefcffffeefed
        ffffefffffffeffcbbbbbbddbbbd1dddbbbd1dddbbbdddddbbbdddddbbbdddddbbbdddddbbbdddddbbbdddddbbddddddbbddddddbbddddddbbddddddbbd1ddddbbd1ddddbbd1dbcffffefffffffeffb
        ffffefffffffeffcbeebbbbbdbbddddddbbddddddbbddbdddbbddddddbbddbdddbbddddddbbddbdddbdddddddbdddbdddbdddddddbdddbdddbdddddddbddbbdddbdddddddbddbbeffffefffffffeffb
        fffffffffffffffebbebbbbdddbdddddddbdddddddbddbbddbbddddddbbdbbbddbbddddddbddbbdddbdddddddbddbbdddbdddddddbddbbdddbdddddddbddbbdddbdddddddbddbbefffffffffffffffb
        fefffffffefffffebbbbbbbbbbbddddddbbddddddbbddddddbbddddddbbdddddbbbdddddbbbdddddbbbdddddbbbdddddbbbdddddbbddddddbbddddddbbddddddbbddddddbbddddefefffffffefffffb
        fcffeefffcffeffebbbbbbbbbbbdbdddbbbbbbbdbbbbbbbdbbbbbbbdbbbbbbbdbbbbbbbdbbbbbbbdbbbbbbbdbbbbbbbdbbbbbbbdbbbbbbbdbbbbbbbdbbbbbbbdbbbbbbbdbbbbbbcfcffeefffcffeefb
        fffeeefffffeeffeebbbbbbbbbbbdddbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbcfffeeefffffeeffb
        fffeeeeffffeefeeebbbbdbbbbbbddbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbefffeeeeffffeefed
        fffcefeffffcefcebbbbbbbbddbbbbbbbbbbbbbbdbbbbbbbbbbbbbbbdbbbbbbbbbbbbbbddbbbbbbbbbbbbbbddbbbbbbbbbbbbbbddbbbbbbbbbbbbbbddbbbbbbbbbbbbbbddbbbbbcffffefeffffcefcd
        ffffefffffffeffcbbbbbbbd1dddddbbbbbbbbbdddddddbbbbbbbbbddddddbbbbbbbbbdddddddbbbbbbbbbdddddddbbbbbbbbbdddddddbbbbbbbbbdddddddbbbbbbbbbdddddddbcffffefffffffeffb
        ffffefffffffeffcbeebbbbddddddbbbbbbbbbbddddddbbbbbbbbbbddddddbbbbbbbbbbddddddbbbbbbbbbdddddddbbbbbbbbbdddddddbbbbbbbbbdddddddbbbbbbbbbdddddddbcffffefffffffeffb
        fffffffffffffffebbbbddbdddbdddbbbbbdddbddbbdddbbbbbddbbddbbddbbbbbbddbdddbbddbbbbbbddbdddbbddbbbbbbddbdddbbddbbbbbbddbdddbbddbbbbbbddbdddbbddbefffffffffffffffb
        fefffffffefffffebbbdddbddbbdddbddbbdddbddbbddbbddbbddbbddbbddbbddbbddbbddbbddbbdbbbddbdddbdddbddbbdddbddbbdddbddbbdddbddbbdddbddbbdddbddbbdddbcfefffffffefffffb
        ffffeeffffffeffebbddddbdbbddddbdddddddbdbbddddbddddddbbdbbdddbbddddddbbdbbdddbbddddddbddbbdddbdddddddbddbddddbdddddddbddbddddbdddddddbddbddddbcffffeeffffffeefb
        fffeeffffffeeffebbbbddbbdbbbdbbbdbbbdbbbdbbbdbbbdbbbdbbbdbbbdbbbdbbbdbbbdbbbdbbddbbbdbbbdbbddbbddbbddbbddbbddbbddbbddbbddbbddbbddbbddbbddbbddbcfffeeffffffeeffb
        fffeefeffffeefeebbbbbdbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbcfffeefcffffeefed
        ffffefffffffefcebbbbbbddbbbdddbbbbbdddbbbbbdddbbbbbdddbbbbbddbbbbbbddbbbbbbddbbbbbbddbbbbbbddbbbbbbddbbbbbbddbbbbbbddbbbbbbddbbbbbbddbbbbbbddbcffffefffffffeffb
        ffffefffffffeffcbbbbbbbddbbddddddbbdddddbbbdddddbbbdddddbbbdddddbbbdddddbbbdddddbbbdddddbbddddddbbddddddbbddddddbbddddddbbddddddbbddddddbbddddcffffefffffffeffb
        ffffefffffffeffcbeebbbbbddbdddddddbddddddbbddbbddbbddddddbbddbdddbbddddddbbddbdddbdddddddbddbbdddbdddddddbddbbdddbdddddddbddbbdddbdddddddbddbbeffffefffffffeffb
        fffffffffffffffebbebebbbddbddddddbbddddddbbddbdddbbddddddbbddbdddbbddddddbbddbdddbdddddddbddbbdddbdddddddbddbbdddbdddddddbddbbdddbdddddddbddbbefffffffffffffffb
        fefffffffefffffebbbbbbbbbdbddddddbbdddddbbbdddddbbbdddddbbbdddddbbbdddddbbbdddddbbbdddddbbbdddddbbbdddddbbddddddbbddddddbbddddddbbddddddbbdddbefefffffffefffffb
        fffeeefffffeeffebbbbbbbdbbbdbbdddbbbbbbbdbbbbbbbdbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbdbbbbbbbdbbbbbbbdbbbbbbbdbbbbbbbdbbbbbbcfffceefffffceefb
        fffeeefffffeeffeebbbbbbbbbbbddbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbdbbbbbbbdbbbbbbbdbbbbbcfffeeefffffeeffb
        fffeeeeffffeefeeebbebdbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbefffeeeeffffeefed
        ffffefffffffeffebbbbbbbdddbbbbbbbbbbbbbdddbbbbbbbbbbbbbdddbbbbbbbbbbbbbdddbbbbbbbbbbbbbddbbbbbbbbbbbbbbddbbbbbbbbbbbbbbddbbbbbbbbbbbbbdddbbbbbcffffffffffffeffb
        ffffefffffffeffcbbbbbbbddddddbbbbbbbbbbddddddbbbbbbbbbbddddddbbbbbbbbbbddddddbbbbbbbbbdddddddbbbbbbbbbdddddddbbbbbbbbbdddddddbbbbbbbbbdddddddbcffffefffffffeffb
        ffffeffffffffffebbebbbbdddddddbbbbbbbbbdddddddbbbbbbbbbddddddbbbbbbbbbdddddddbbbbbbbbbdddddddbbbbbbbbbdddddddbbbbbbbbbdddddddbbbbbbbbbdddddddbefffffffffffffffb
        fffffffffffffffebbbbddbddbbbdbbbbbbbdbbddbbbdbbbbbbbdbbddbbddbbbbbbbdbbddbbddbbbbbbddbdddbbddbbbbbbddbdddbbddbbbbbbddbdddbbddbbbbbbddbdddbbddbefffffffffffffffb
        fefffffffefffffebbddddbddbddddbddbddddbddbddddbddbddddbdbbdddbbddbdddbddbbdddbdddbdddbddbbdddbdddbdddbddbbdddbddbbdddbddbbdddbddbbdddbddbbdddbcfefffffffefffffb
        fffeeefffffeeefebdbbddbdbdbbdbbdddbddbbdbdbddbbdddbddbbdbdbddbbdddbddbbdbdbddbbdddbddbbdbbbddbddddbddbdddbbddbddddbddbdddbbddbdddbbddbdddbbddbcfffeeefffffeeefb
        fffeeffffffeeffebbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbdbbbddbbdbbddbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbcfffeeffffffeeffb
        fffeefeffffeefeecceeeeeecceeeeeecceeeeeecceeeeebbbbbbdbbbbbbbbbecceeeeeecceeeeeecceeeeeecceeeeeecceeeeeecceeeeeecceeeeeecceeeeeeceeeeeeeceeeeeefffeefeffffeefed
        ffffffffffffffffffffefffffffefffffffefffffffefcbbbbbbbddbbbdddeffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffeffffffffffffffffffb
        ffffefffffffefffffffefffffffefffffffefffffffeffcbbbbbbbbdbbdddbcffffefffffffefffffffeffffffeeffffffefffffffefffffffefffffffefffffffefffffffefffffffefffffffeffb
        fffffffffffffffffffffffffffffffffffffffffffffffebeebbbbdddbdddbcffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffb
        fffffffffffffffffffffffffffffffffffffffffffffffebbbbebbbdbbdddbcffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffb
        fefffffffefffffffefffffffefffffffefffffffefffffebbbbbbbbbdbdddbcfefffffffefffffffefffffffcffffffecffffffecffffffefffffffefffffffefffffffefffffffefffffffefffffb
        fffeeefffffeeefffffeeefffffeeffffffeeefffffeeffebbbbbbbdbbbdbbbffffeeffffffeeffffffeefffffeeefffffeeefffffeeefffffeeefffffeeefffffeeefffffeeefffffeeefffffeeefb
        fffeeefffffeeffffffeeefffffeeffffffeeefffffeefceebbbbdbbbbbbddbffffeeffffffefffffffeeffffffefffffffeeffffffefffffffeeffffffefffffffeeffffffeffffffeeefffffeeffb
        fffeeeeffffeefeffffeeeeffffeefeffffeeeeffffeffeeebbebdbbbbbbbbeffffeeeeffffeffeffffeeeefffeeffefffeeeeefffeefcefffeeeeefffeefcffffeeeeefffeefeffffeeeeffffeefed
        ffffffffffffffffffffffffffffffffffffffffffffffcbbbbbbbbdddbdbbcfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffb
        ffffefffffffefffffffefffffffefffffffefffffffeffcbebbbbbddddddbefffffefffffffeffffffeeffffffeeffffffecffffffecffffffefffffffefffffffefffffffefffffffefffffffeffb
        fffffffffffffffffffffffffffffffffffffffffffffffebbbbbbbdddddddecffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffb
        fffffffffffffffffffffffffffffffffffffffffffffffebbbbdbbddbbbdbecffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffb
        fefffffffefffffffefffffffefffffffefffffffefffffebbddddbdbbddddcffefffffffeffffffeeffffffeeffffffeeffffffecffffffefffffffefffffffefffffffefffffffefffffffefffffb
        fffeeefffffeeefffffeeefffffeeffffffeeffffffeeffebdbbdbbdddbbdbcffffeefffffeeefffffeeefffffeeefffffeeefffffeeefffffeeefffffeeefffffeeefffffeeefffffeeefffffeeefb
        cffeeccfcffeeccfcffeeccfcffeeccfcffeeccfcfceecebdbbdddbbdbbdddbccfceeccccfceeccccfceeccccfceeccccfceeccccfceeccccfceccccffeeccfcffeeccfcffeeccfcffeeccfcffeeccd
        dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd1
        `]
    encontrar_indice = lista_escenario[id]
    scene.setBackgroundImage(encontrar_indice)
    lista_posicion_x = [71, 1]
    lista_posicion_y = [120, 1]
    colision = sprites.create(img`
        6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 
        6 9 9 9 6 6 9 9 9 9 6 6 9 9 9 6 
        6 9 9 6 6 9 9 c c 9 9 6 6 9 9 6 
        6 9 6 6 9 9 c c 6 9 9 9 6 6 9 6 
        6 6 6 9 9 9 9 c 6 6 9 9 9 6 6 6 
        6 6 9 9 9 9 9 9 6 6 9 9 9 9 6 6 
        6 9 9 9 6 6 6 6 9 6 9 9 c 9 9 6 
        6 9 c 6 6 6 9 9 9 6 9 c c c 9 6 
        6 9 c c c 9 6 9 9 9 6 6 6 c 9 6 
        6 9 9 c 9 9 6 9 6 6 6 6 9 9 9 6 
        6 6 9 9 9 9 6 6 9 9 9 9 9 9 6 6 
        6 6 6 9 9 9 6 6 c 9 9 9 9 6 6 6 
        6 9 6 6 9 9 9 6 c c 9 9 6 6 9 6 
        6 9 9 6 6 9 9 c c 9 9 6 6 9 9 6 
        6 9 9 9 6 6 9 9 9 9 6 6 9 9 9 6 
        6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 
        `, SpriteKind.objeto_colision)
    colision.setPosition(71, 120)
}
let lista_posicion_y: number[] = []
let lista_posicion_x: number[] = []
let encontrar_indice: Image = null
let lista_escenario: Image[] = []
let lista_id_escenario: number[] = []
let colision: Sprite = null
let main_character: Sprite = null
crear_escenario(0)
movimiento_jugador(true)
